#! /bin/bash

echo $1
testerDirectory="/home/ssdavis/60/p2/Testing"

if [ $# -ne 1 ]; then
  echo "usage testhw: testhw source_directory" 1>&2
  exit
fi

if [[ $1 =~ Testing ]]; then # Use from this directory is not allowed
  echo "You may not use Testing as your own source directory!"  1>&2
  exit
fi

cd $1
echo -n "Scores from p2 for " > results.txt

if [ -e authors.csv ]; then
  dos2unix -q authors.csv
  awk -F, '{printf"%s,%s ", $2, $3}' authors.csv >> results.txt
  awk -F, '{printf"%s,%s\n", $2, $3}' authors.csv > names.txt
  echo -e "\n\nNote that the format for authors.csv is: e-mail<comma>last name<comma>first name" >> results.txt
  echo "For example: ssdavis@ucdavis.edu,Davis,Sean"  >> results.txt
  awk -F, {'printf"%s ", $1'} authors.csv > addresses
else
  echo  "You need to create an authors.csv file!!!! No one will receive credit for this assignment"  >> results.txt
  echo "$1@ucdavis.edu" > addresses
  finger ${PWD##*/} | awk 'NR == 1 {printf"%s,%s", $NF, $4}' > names.txt
fi

echo -en "\nAddresses used: " >> results.txt
cat addresses >> results.txt
echo " " >> results.txt
echo "Directory: $1"

rm -f  BTree.h BTreeNode.cpp BTreeNode.h QueueAr.cpp QueueAr.h vector.h vector.cpp dsexceptions.h BTree test*.txt > /dev/null
cp $testerDirectory/*.cpp $testerDirectory/*.h $testerDirectory/MakefileTesting $testerDirectory/*.dat . 

make  -f MakefileTesting
Score=0


  if [ -e BTree ]; then
    rm -f test*.txt
    echo BTree1.dat 3 4: >> results.txt
    echo BTree1.dat 3 4
    (BTree BTree1.dat 3 4 | tail -20 > test1.txt)&
    sleep 1
    pkill BTree
    diff $testerDirectory/test1.txt test1.txt > diff.txt
    if [ ! -s diff.txt ]; then
      (( Score += 5 ))
      echo OK >> results.txt
    else
      echo "Yours: " >> results.txt
      tail -20 test1.txt >> results.txt
      echo -e "\nSean's: " >> results.txt
      tail -20 $testerDirectory/test1.txt >> results.txt
    fi
    echo " " >> results.txt

    echo BTree2.dat 3 4: >> results.txt
    echo BTree2.dat 3 4
    (BTree BTree2.dat 3 4 | tail -20 > test2.txt)&
    sleep 1
    pkill BTree
    diff $testerDirectory/test2.txt test2.txt > diff.txt
    if [ ! -s diff.txt ]; then
      (( Score += 5 ))
      echo OK >> results.txt
    else
      echo "Yours: " >> results.txt
      tail -20 test2.txt >> results.txt
      echo -e "\nSean's: " >> results.txt
      tail -20 $testerDirectory/test2.txt >> results.txt
    fi
 
    echo "  " >> results.txt

    echo BTree5.dat 3 4: >> results.txt
    echo BTree5.dat 3 4
    (BTree BTree5.dat 3 4 | tail -20 > test3.txt)&
    sleep 1
    pkill BTree
    diff $testerDirectory/test3.txt test3.txt > diff.txt
    if [ ! -s diff.txt ]; then
      (( Score += 5 ))  
      echo OK >> results.txt
    else
      echo "Yours: " >> results.txt
      tail -20 test3.txt >> results.txt
      echo -e "\nSean's: " >> results.txt
      tail -20 $testerDirectory/test3.txt >> results.txt
    fi
 
    echo " " >> results.txt

    echo BTree12.dat 3 4: >> results.txt
    echo BTree12.dat 3 4
    (BTree BTree12.dat 3 4 | tail -20 > test4.txt)&
    sleep 1
    pkill BTree
    diff $testerDirectory/test4.txt test4.txt > diff.txt
    if [ ! -s diff.txt ]; then
      (( Score += 5 ))
      echo OK >> results.txt
    else
      echo "Yours: " >> results.txt
      tail -20 test4.txt >> results.txt
      echo -e "\nSean's: " >> results.txt
      tail -20 $testerDirectory/test4.txt >> results.txt
    fi
 
    echo " " >> results.txt

    echo BTree25.dat 3 4: >> results.txt
    echo BTree25.dat 3 4
    (BTree BTree25.dat 3 4 | tail -20 > test5.txt)&
    sleep 1
    pkill BTree
    diff $testerDirectory/test5.txt test5.txt > diff.txt
    if [ ! -s diff.txt ]; then
      (( Score += 5 ))
      echo "OK" >> results.txt
    else
      echo "Yours: " >> results.txt
      tail -20 test5.txt >> results.txt
      echo -e "\nSean's: " >> results.txt
      tail -20 $testerDirectory/test5.txt >> results.txt
    fi
 
    echo " " >> results.txt


    echo BTree5.dat 5 2: >> results.txt
    echo BTree5.dat 5 2
    (BTree BTree5.dat 5 2 | tail -20 > test6.txt)&
    sleep 1
    pkill BTree
  diff $testerDirectory/test6.txt test6.txt > diff.txt
    if [ ! -s diff.txt ]; then
      (( Score += 5 ))
      echo OK >> results.txt
    else
      echo "Yours: " >> results.txt
      tail -20 test6.txt >> results.txt
      echo -e "\nSean's: " >> results.txt
      tail -20 $testerDirectory/test6.txt >> results.txt
    fi
 
    echo " " >> results.txt


  
    echo BTree12.dat 5 2: >> results.txt
    echo BTree12.dat 5 2
    (BTree BTree12.dat 5 2 | tail -20  > test7.txt)&
    sleep 1
    pkill BTree
    diff $testerDirectory/test7.txt test7.txt > diff.txt
    if [ ! -s diff.txt ]; then
      (( Score += 5 ))
      echo OK >> results.txt
    else
      echo "Yours: " >> results.txt
      tail -20 test7.txt >> results.txt
      echo -e "\nSean's: " >> results.txt
      tail -20 $testerDirectory/test7.txt >> results.txt
    fi
 
    echo " " >> results.txt

  
    echo BTree25.dat 5 2:  >> results.txt
    echo BTree25.dat 5 2
    (BTree BTree25.dat 5 2 | tail -20  > test8.txt)&
    sleep 1
    pkill BTree
    diff $testerDirectory/test8.txt test8.txt > diff.txt
    if [ ! -s diff.txt ]; then
      (( Score += 5 ))
      echo OK >> results.txt
    else
      echo "Yours: " >> results.txt
      tail -20 test8.txt >> results.txt
      echo -e "\nSean's: " >> results.txt
      tail -20 $testerDirectory/test8.txt >> results.txt
    fi
 
    echo " " >> results.txt


    echo BTree12.dat 2 6: >> results.txt
    echo BTree12.dat 2 6 
    (BTree BTree12.dat 2 6 | tail -20 > test9.txt)&
    sleep 1
    pkill BTree
    diff $testerDirectory/test9.txt test9.txt > diff.txt
    if [ ! -s diff.txt ]; then
      (( Score += 5 ))
      echo OK >> results.txt
    else
      echo "Yours: " >> results.txt
      tail -20 test9.txt >> results.txt
      echo -e "\nSean's: " >> results.txt
      tail -20 $testerDirectory/test9.txt >> results.txt
    fi
 
    echo " " >> results.txt

  
    echo BTree25.dat 2 6: >> results.txt
    echo BTree25.dat 2 6
    (BTree BTree25.dat 2 6 | tail -20 > test10.txt )&
    sleep 1
    pkill BTree
    diff $testerDirectory/test10.txt test10.txt > diff.txt
    if [ ! -s diff.txt ]; then
      (( Score += 5 ))
      echo OK >> results.txt
    else
      echo "Yours: " >> results.txt
      tail -20 test10.txt >> results.txt
      echo -e "\nSean's: " >> results.txt
      tail -20 $testerDirectory/test10.txt >> results.txt
    fi
 
    echo " " >> results.txt

  else
    echo No BTree. >> results.txt
  fi

rm -f core.* >& /dev/null
echo "Total score: $Score" >> results.txt

# mailx -s "ECS 60 P2 Test Results" `cat addresses` < results.txt
#

#awk 'NR == 1 {printf"%s,", $0}' names.txt >> ../results.csv
# echo "${1%%/},$Score" >> ../results.csv
# authorCount=$(grep "@" authors.csv | wc -l)
#
#if [ $authorCount -gt 1 ]; then
#  awk 'NR == 2 {printf"%s,", $0}' names.txt >> ../results.csv
#  echo "${1%%/}, $Score" >> ../results.csv
# fi
#                                                               
