#! /bin/bash

executableName=market.out
maxSleep=420     # 7 minutes
tooLong=0
errorCount=0
MakefileScore=0
CPUTime=0
CPUScore=0
SimTime=0
SimTimeScore=0

echo $1
testerDirectory="/home/ssdavis/60/p4/Testing"

if [ $# -ne 1 ]; then
  echo "usage testhw: testhw source_directory" 1>&2
  exit
fi

if [[ $1 =~ Testing ]]; then # Use from this directory is not allowed
  echo "You may not use Testing as your own source directory!"  1>&2
  exit
fi

cd $1

echo -n "Scores from p5 for " >> results.txt

if [ -e authors.csv ]; then
  dos2unix -q authors.csv
  awk -F, '{printf"%s,%s ", $2, $3}' authors.csv >> results.txt
  awk -F, '{printf"%s,%s\n", $2, $3}' authors.csv > names.txt
  echo -e "\n\nNote that the format for authors.csv is: e-mail<comma>last name<comma>first name" >> results.txt
  echo "For example: ssdavis@ucdavis.edu,Davis,Sean"  >> results.txt
  awk -F, {'printf"%s ", $1'} authors.csv > addresses
else
  echo  "You need to create an authors.csv file!!!! No one will receive credit for this assignment"  >> results.txt
  echo "$1@ucdavis.edu" > addresses
  finger ${PWD##*/} | awk 'NR == 1 {printf"%s,%s", $5, $4}' > names.txt
fi

echo -en "\nAddresses used: " >> results.txt
cat addresses >> results.txt
echo " " >> results.txt
echo "Directory: $1"

echo "This is a run of p5 with a seven minute limit on the time allowed per run."  >> results.txt
#echo "I  will look at the results tomorrow, and see if any that didn't complete before do now." >> results.txt

echo -n "Scores from p4 for " >> results.txt
cat names.txt >> results.txt


rm -f *.out *.o  core* MarketDriver.* CPUTimer* results* market*[890].txt market*[890].sol &> /dev/null

if grep "#include *<" *.cpp *.h | egrep -v "(iostream|cstddef|cstdlib|cstring|climits)" >& /dev/null ; then
  echo "Found #include of standard library other than iostream, cstdlib, cstring, climits, and cstddef." >> results.txt
  echo "so zero for the assignment." >> results.txt
  (( errorCount++ ))
fi

ln -s  $testerDirectory/*.h $testerDirectory/*.cpp $testerDirectory/*.txt $testerDirectory/*.sol  . 

if [ -e *akefile ]; then
  echo "Makefile optimization check: " >> results.txt
  cat *akefile* | grep O > temp
  if [ -s temp ]; then
    (( errorCount++ ))
    cat  temp >> results.txt
    echo "Optimization flag found in Makefile so zero for assignment." >> results.txt
  else
    echo "OK" >> results.txt
  fi
else
 echo "No Makefile found so using default, -1 from total." >> results.txt
 #echo "If your code doesn't work with that Makefile, then handin only a Makefile, and e-mail Sean." >> results.txt
 cp  $testerDirectory/Makefile .
 MakefileScore=-1
fi
 
make &> /dev/null

if [ -s $executableName ]; then
  rm totalTemp &> /dev/null 
  echo "Testing  market-3792-1000000-100000-8.txt: " >> results.txt
  echo $executableName $testerDirectory/market-3792-1000000-100000-8.txt
  ($executableName $testerDirectory/market-3792-1000000-100000-8.txt | tail | tee -a totalTemp  > temp)&
  count=0 

  while [[ $count -lt $maxSleep ]]; do
    sleep 1
    (( count += 1 ))
    ps | grep $executableName > temp2
    echo $count

    if [ ! -s temp2 ]; then
      cat temp 
      break
    fi
  done

  pkill $executableName &> /dev/null
  rm core &> /dev/null

  if [ ! -s temp ]; then
    echo "$executableName did not finish in 2 minutes or seg faulted so you will receive a zero." >> results.txt
    (( tooLong++ ))
  else 
    cat temp >> results.txt
    echo " " >> results.txt
    lineCount=$( cat temp | wc -l )

    if [ $lineCount -gt 1 ]; then
      echo "Errors found, so zero for assignment." >> results.txt 
      (( errorCount++ ))
    fi # if more than one line in temp
  fi #if temp not created so didn't finish

  echo "Testing  market-3792-1000000-100-9.txt: " >> results.txt
  echo $executableName $testerDirectory/market-3792-1000000-100-9.txt
  ($executableName $testerDirectory/market-3792-1000000-100-9.txt | tail | tee -a totalTemp  > temp)&
  count=0

  while [[ $count -lt $maxSleep ]]; do
    sleep 1
    (( count += 1 ))
    ps | grep $executableName > temp2
    echo $count

    if [ ! -s temp2 ]; then
      cat temp
      break
    fi
  done

  pkill $executableName &> /dev/null
  rm core &> /dev/null

  if [ ! -s temp ]; then
    echo "$executableName did not finish in 2 minutes or seg faulted so you will receive a zero." >> results.txt
    (( tooLong++ ))
  else
    cat temp >> results.txt
    echo " " >> results.txt
    lineCount=$( cat temp | wc -l )

    if [ $lineCount -gt 1 ]; then
      echo "Errors found, so zero for assignment." >> results.txt
      (( errorCount++ ))
    fi # if more than one line in temp
  fi #if temp not created so didn't finish

  echo "Testing market-100-1000000-1000-10.txt : " >> results.txt
  echo $executableName $testerDirectory/market-100-1000000-1000-10.txt
  ($executableName $testerDirectory/market-100-1000000-1000-10.txt | tail | tee -a totalTemp  > temp)&
  count=0

  while [[ $count -lt $maxSleep ]]; do
    sleep 1
    (( count += 1 ))
    ps | grep $executableName > temp2
    echo $count

    if [ ! -s temp2 ]; then
      cat temp
      break
    fi
  done

  pkill $executableName &> /dev/null
  rm core &> /dev/null

  if [ ! -s temp ]; then
    echo "$executableName did not finish in 2 minutes or seg faulted so you will receive a zero." >> results.txt
    (( tooLong++ ))
  else
    cat temp >> results.txt
    echo " " >> results.txt
    lineCount=$( cat temp | wc -l )

    if [ $lineCount -gt 1 ]; then
      echo "Errors found, so zero for assignment." >> results.txt
      (( errorCount++ ))
    fi # if more than one line in temp
  fi #if temp not created so didn't finish

   cat totalTemp | awk '/CPU/ {CPU += $2} \
    END {print CPU, int(25 *  2.04 / CPU + 0.9)}' > scores.txt
  CPUTime=$( awk '{print $1}' scores.txt )
  CPUScore=$( awk '{print $2}' scores.txt )

  if [ $CPUScore -gt 30 ]; then
    CPUScore=30
  fi

  echo -e "\nTotal CPU Time: Yours $CPUTime  Sean's: 2.04 so your score is $CPUScore"  >> results.txt
  if [ $tooLong -gt 0 ]; then
    echo 'Total Score: Zero because it did not complete in time.'  >> results.txt
    finalScore=0
  else
    if [[ $errorCount -gt 0 ]]; then
      echo 'Total Score: Zero because there were errors found while running.' >> results.txt
      finalScore=0
    else
      finalScore=$(( $CPUScore + 25 + $MakefileScore))
      echo "Total score: $CPUScore + 25 + $MakefileScore = $finalScore" >> results.txt
    fi # if errors
  fi # if too long 
else
  echo "$executableName was not created by make, so zero for assignment." >> results.txt
fi


#mailx -s "ECS 60 P5 Test Results" `cat addresses` < results.txt


#awk 'NR == 1 {printf"%s,", $0}' names.txt >> ../results.csv
#echo "${1%%/},$finalScore,$errorCount,$tooLong,$CPUScore,$SimTimeScore" >> ../results.csv
#authorCount=$(grep "@" authors.csv | wc -l)

#if [ $authorCount -gt 1 ]; then
#  awk 'NR == 2 {printf"%s,", $0}' names.txt >> ../results.csv
#  echo "${1%%/},$finalScore,$errorCount,$tooLong,$CPUScore,$SimTimeScore" >> ../results.csv
#  fi

